/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 11-Nov-2017 10:46:54 p.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cnchequera_pk_chequera_seq
;

DROP SEQUENCE IF EXISTS cnplancontable_pk_plancontable_seq
;

DROP SEQUENCE IF EXISTS cnproyecto_pk_proyecto_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS cnChequera CASCADE
;

DROP TABLE IF EXISTS cnPlanContable CASCADE
;

DROP TABLE IF EXISTS cnProyecto CASCADE
;

/* Create Tables */

CREATE TABLE cnChequera
(
	pk_Chequera integer NOT NULL   DEFAULT NEXTVAL(('"cnchequera_pk_chequera_seq"'::text)::regclass),    --  
	fkBanco integer NOT NULL,
	fkCuentaContable integer NOT NULL,
	cnDescripcion varchar(50) NULL,
	cnNroInicio varchar(20) NOT NULL,
	cnNroFin varchar(20) NOT NULL,
	cnHabilitar char(1) NOT NULL,
	cnEstado char(1) NOT NULL
)
;

CREATE TABLE cnPlanContable
(
	pk_PlanContable integer NOT NULL   DEFAULT NEXTVAL(('"cnplancontable_pk_plancontable_seq"'::text)::regclass),
	cnCuentaContable char(13) NOT NULL,
	cnDescripcion varchar(50) NULL,
	fkMoneda integer NOT NULL,
	cnNivel integer NOT NULL,
	cnCtaChica char(1) NULL,
	cnCtaCte char(1) NULL,
	cnCtaFlujo char(1) NULL,
	cnCtaPresu char(1) NULL,
	cnEstado char(1) NOT NULL,
	cnCuentaPadre integer NULL
)
;

CREATE TABLE cnProyecto
(
	pk_Proyecto integer NOT NULL   DEFAULT NEXTVAL(('"cnproyecto_pk_proyecto_seq"'::text)::regclass),
	cnNombre varchar(50) NULL,
	cnCodigo char(6) NULL,
	cnClave varchar(25) NULL,
	cnGlosa varchar(50) NULL,
	cnBreve varchar(15) NULL,
	fkCtaCosto integer NOT NULL,
	cnEstado char(1) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cnChequera ADD CONSTRAINT PK_cnChequera
	PRIMARY KEY (pk_Chequera)
;

ALTER TABLE cnPlanContable ADD CONSTRAINT PK_cnPlanContable
	PRIMARY KEY (pk_PlanContable)
;

ALTER TABLE cnProyecto ADD CONSTRAINT pk_Proyecto
	PRIMARY KEY (pk_Proyecto)
;

/* Create Foreign Key Constraints */

ALTER TABLE cnChequera ADD CONSTRAINT FK_cnChequera_cnPlanContable
	FOREIGN KEY (fkCuentaContable) REFERENCES cnPlanContable (pk_PlanContable) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnPlanContable ADD CONSTRAINT FK_fkMoneda
	FOREIGN KEY (fkMoneda) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnProyecto ADD CONSTRAINT FK_cnProyecto_cnPlanContable
	FOREIGN KEY (fkCtaCosto) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN cnChequera.pk_Chequera
	IS ' '
;

CREATE SEQUENCE cnchequera_pk_chequera_seq INCREMENT 1 START 1
;

COMMENT ON CONSTRAINT FK_fkMoneda ON cnPlanContable IS 'Foreign key constraint'
;

CREATE SEQUENCE cnplancontable_pk_plancontable_seq INCREMENT 1 START 1
;

CREATE SEQUENCE cnproyecto_pk_proyecto_seq INCREMENT 1 START 1
;
