/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 08-Nov.-2017 10:00:16 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cnbanco_pk_banco_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS cnBanco CASCADE
;

/* Create Tables */

CREATE TABLE cnBanco
(
	pk_Banco integer NOT NULL   DEFAULT NEXTVAL(('"cnbanco_pk_banco_seq"'::text)::regclass),
	cnCodigo char(4) NOT NULL,
	cnNombre varchar(50),
	cnDireccion varchar(50),
	cnObservacion varchar(50)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cnBanco ADD CONSTRAINT PK_cnBanco
	PRIMARY KEY (pk_Banco)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE cnbanco_pk_banco_seq INCREMENT 1 START 1
;
