/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 13-Nov.-2017 5:43:44 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cndetcomprobante_pk_detcomprobante_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS cnDetComprobante CASCADE
;

/* Create Tables */

CREATE TABLE cnDetComprobante
(
	pk_DetComprobante integer NOT NULL   DEFAULT NEXTVAL(('"cndetcomprobante_pk_detcomprobante_seq"'::text)::regclass),
	fkComprobante integer NOT NULL,
	fkCuentaContable integer NOT NULL,
	cnDebeE decimal(10,2),
	cnHaberE decimal(10,2),
	cnDebeN decimal(10,2),
	cnHaberN decimal(10,2),
	fkCtaCte integer,    -- identificador de cuenta corriente
	fkProyecto integer,    -- identificador de proyecto
	fkctaFlujo integer,
	fkDocument integer,
	cnNroDoc varchar(25),
	cnFechaVenc timestamp,
	cnGlosaDet varchar(100)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cnDetComprobante ADD CONSTRAINT PK_cnDetComprobante
	PRIMARY KEY (pk_DetComprobante)
;

/* Create Foreign Key Constraints */

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnComprobante
	FOREIGN KEY (fkComprobante) REFERENCES cnComprobante (pk_Comprobante) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnCuentaCte
	FOREIGN KEY (fkCtaCte) REFERENCES cnCuentaCte (pk_CuentaCte) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnCuentaFlujo
	FOREIGN KEY (fkctaFlujo) REFERENCES cnCuentaFlujo (pk_CuentaFlujo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnDocumento
	FOREIGN KEY (fkDocument) REFERENCES cnDocumento (pk_Document) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnPlanContable
	FOREIGN KEY (fkCuentaContable) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnProyecto
	FOREIGN KEY (fkProyecto) REFERENCES cnProyecto (pk_Proyecto) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN cnDetComprobante.fkCtaCte
	IS 'identificador de cuenta corriente'
;

COMMENT ON COLUMN cnDetComprobante.fkProyecto
	IS 'identificador de proyecto'
;

CREATE SEQUENCE cndetcomprobante_pk_detcomprobante_seq INCREMENT 1 START 1
;
