/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 08-Nov.-2017 9:02:28 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cnmoneda_pk_moneda_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS cnMoneda CASCADE
;

/* Create Tables */

CREATE TABLE cnMoneda
(
	pk_Moneda integer NOT NULL   DEFAULT NEXTVAL(('"cnmoneda_pk_moneda_seq"'::text)::regclass),    --   
	cnSimbolo varchar(15),
	cnDescripcion varchar(25)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cnMoneda ADD CONSTRAINT pk_cnMoneda
	PRIMARY KEY (pk_Moneda)
;

ALTER TABLE cnMoneda ADD CONSTRAINT UQ_cnMoneda_pk_Moneda UNIQUE (pk_Moneda)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN cnMoneda.pk_Moneda
	IS '  '
;

CREATE SEQUENCE cnmoneda_pk_moneda_seq INCREMENT 1 START 1
;
