/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 13-Nov.-2017 11:55:37 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cnproyecto_pk_proyecto_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS cnProyecto CASCADE
;

/* Create Tables */

CREATE TABLE cnProyecto
(
	pk_Proyecto integer NOT NULL   DEFAULT NEXTVAL(('"cnproyecto_pk_proyecto_seq"'::text)::regclass),
	cnNombre varchar(50),
	cnCodigo char(6),
	cnClave varchar(25),
	cnGlosa varchar(50),
	cnBreve varchar(15),
	fkCtaCosto integer NOT NULL,
	cnEstado char(1) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cnProyecto ADD CONSTRAINT pk_Proyecto
	PRIMARY KEY (pk_Proyecto)
;

/* Create Foreign Key Constraints */

ALTER TABLE cnProyecto ADD CONSTRAINT FK_cnProyecto_cnPlanContable
	FOREIGN KEY (fkCtaCosto) REFERENCES cnPlanContable (pk_PlanContable) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE cnproyecto_pk_proyecto_seq INCREMENT 1 START 1
;
