/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 14-Nov-2017 02:19:12 a.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cncomprobante_pk_comprobante_seq
;

DROP SEQUENCE IF EXISTS cndetcomprobante_pk_detcomprobante_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS cnComprobante CASCADE
;

DROP TABLE IF EXISTS cnDetComprobante CASCADE
;

/* Create Tables */

CREATE TABLE cnComprobante
(
	pk_Comprobante integer NOT NULL   DEFAULT NEXTVAL(('"cncomprobante_pk_comprobante_seq"'::text)::regclass),
	cnCodComp char(5) NULL,
	cnTComp integer NOT NULL,
	cnNroComp varchar(15) NULL,
	cnFechaComp timestamp NULL,
	fkMoneda integer NOT NULL,
	cnTCambio decimal(10,2) NULL,
	fkBanco integer NULL,
	cnCliente varchar(50) NULL,
	cnGlosa varchar(100) NULL,
	cnEstado char(1) NULL
)
;

CREATE TABLE cnDetComprobante
(
	pk_DetComprobante integer NOT NULL   DEFAULT NEXTVAL(('"cndetcomprobante_pk_detcomprobante_seq"'::text)::regclass),
	fkComprobante integer NOT NULL,
	fkCuentaContable integer NOT NULL,
	cnDebe decimal(10,2) NULL,
	cnHaber decimal(10,2) NULL,
	fkCtaCte integer NULL,    -- identificador de cuenta corriente
	fkProyecto integer NULL,    -- identificador de proyecto
	fkDocument integer NULL,
	cnNroDoc varchar(25) NULL,
	cnGlosaDet varchar(100) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cnComprobante ADD CONSTRAINT PK_cnComprobante
	PRIMARY KEY (pk_Comprobante)
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT PK_cnDetComprobante
	PRIMARY KEY (pk_DetComprobante)
;

CREATE INDEX IXFK_cnDetComprobante_cnPlanContable ON cnDetComprobante (fkCuentaContable ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE cnComprobante ADD CONSTRAINT FK_cnComprobante_cnBanco
	FOREIGN KEY (fkBanco) REFERENCES cnBanco (pk_Banco) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnComprobante ADD CONSTRAINT FK_cnComprobante_cnMoneda
	FOREIGN KEY (fkMoneda) REFERENCES cnMoneda (pk_Moneda) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnComprobante
	FOREIGN KEY (fkComprobante) REFERENCES cnComprobante (pk_Comprobante) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnCuentaCte
	FOREIGN KEY (fkCtaCte) REFERENCES cnCuentaCte (pk_CuentaCte) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnDocumento
	FOREIGN KEY (fkDocument) REFERENCES cnDocumento (pk_Document) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnPlanContable
	FOREIGN KEY (fkCuentaContable) REFERENCES cnPlanContable (pk_PlanContable) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cnDetComprobante ADD CONSTRAINT FK_cnDetComprobante_cnProyecto
	FOREIGN KEY (fkProyecto) REFERENCES cnProyecto (pk_Proyecto) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE cncomprobante_pk_comprobante_seq INCREMENT 1 START 1
;

COMMENT ON COLUMN cnDetComprobante.fkCtaCte
	IS 'identificador de cuenta corriente'
;

COMMENT ON COLUMN cnDetComprobante.fkProyecto
	IS 'identificador de proyecto'
;

CREATE SEQUENCE cndetcomprobante_pk_detcomprobante_seq INCREMENT 1 START 1
;
