/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 15-Nov-2017 09:30:53 a.m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cngrupo_pkgrupo_seq
;

DROP SEQUENCE IF EXISTS cnusuario_pkusuario_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS cnGrupo CASCADE
;

DROP TABLE IF EXISTS cnUsuario CASCADE
;

/* Create Tables */

CREATE TABLE cnGrupo
(
	pkGrupo integer NOT NULL   DEFAULT NEXTVAL(('"cngrupo_pkgrupo_seq"'::text)::regclass),
	codigo varchar(4) NOT NULL,
	descripcion varchar(30) NULL,
	estado char(1) NULL
)
;

CREATE TABLE cnUsuario
(
	pkUsuario integer NOT NULL   DEFAULT NEXTVAL(('"cnusuario_pkusuario_seq"'::text)::regclass),
	fkGrupo integer NOT NULL,
	nickname varchar(50) NULL,
	nombreCompleto varchar(15) NULL,
	apellidoCompleto varchar(50) NULL,
	password varchar(50) NULL,
	estado char(1) NULL,
	email varchar(50) NULL,
	authkey varchar(50) NULL,
	accesstoken varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cnGrupo ADD CONSTRAINT PK_amGrupo
	PRIMARY KEY (pkGrupo)
;

ALTER TABLE cnUsuario ADD CONSTRAINT PK_amUsuario
	PRIMARY KEY (pkUsuario)
;

CREATE INDEX IXFK_cnUsuario_cnGrupo ON cnUsuario (fkGrupo ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE cnUsuario ADD CONSTRAINT FK_cnUsuario_cnGrupo
	FOREIGN KEY (fkGrupo) REFERENCES cnGrupo (pkGrupo) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE cngrupo_pkgrupo_seq INCREMENT 1 START 1
;

CREATE SEQUENCE cnusuario_pkusuario_seq INCREMENT 1 START 1
;
